### ISSUE TITLE
Search by postcode?

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#16]
A comment from a few people has been whether or not a postcode search could be included on the map. This would not change any drop-downs, but ideally you could type a postcode into a box, which could then drop a pin. The purpose of this would be for people with a specific area in mind (but who don't know their LSOA) to work out where they are.

**Comment by gilesdring** [comment]
Design needed - simplest would be postcode search which then recentres the map on the pin.

Issues with this:

1. Changes the way that search works - would probably need a separate search box. Current search is within the area that you're currently looking at.
2. We'd need to integrate with something like postcodes.io, which makes it dependent on that service.
3. If we've dropped a pin, do we need additional interactions to recentre and clear, and what happens if we re-search - move the pin or add a new one. How do we deal with multiple pins?
4. Do we need something like typeahead for postcodes? Full postcode or just outcode (first part)
5. Do we zoom or not
6. We also need a statement of privacy policy stating that we send data to postcodes.io (or similar) to perform postcode lookup

**Comment by xrmitchell** [comment]
One to discuss in our next meeting unless you want to move things on before then @gilesdring?

**Comment by xrmitchell** [comment]
include a link to https://findthatpostcode.uk/ in the FAQs so people can self serve to find their own LSOA

add a geo-search 'find me' button

**Comment by slowe** [comment]
@xrmitchell After a bit of thought, it should now be possible to search for a postcode. When you type something that looks like a full postcode, the search box then requests data from FindThatPostcode and once that comes back it looks for any area codes that match a potential result in the search box.

There will need to be a note about privacy added.

**Comment by xrmitchell** [comment]
What note do we need to add about privacy?

**Comment by xrmitchell** [comment]
I noticed one is added at the bottom already - I'm happy to close this action if you are @slowe
