### ISSUE TITLE
Colour scales not great for some datasets

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#22]
For heat demand + total heat demand - colours hardly change at all between 2030 and 2050 for Local Authorities. If you look at CO2 emissions for non-domestic, there is hardly any change whatsoever in the map

I have a few ideas for consideration, but open to other ideas too!
-  use more than 5 colours be a simple way to improve the relative resolution of the map
- keep a 5-colour scale, but instead of an equal split, have the lightest and darkest represent a <x and >x amounts.

**Comment by xrmitchell** [comment]
A suggestion from an external stakeholder who has done mapping projects before was to make the highest colour band larger, >x, and then split the rest of them evenly. This may show the data better

**Comment by gilesdring** [comment]
We could move to more colour bands - we discussed this at length with @ash001j during the DFES work and ended up with 5 bands. The colour bands are automatically generated, so we'd not be readily able to customise the breaks to make the scale 'visually interesting' as is possible with a custom report.

**Comment by slowe** [comment]
My preference would be a continuous colour scale rather than a banded one. Banded colour scales are more appropriate for paper-based situations where it isn't possible to find out the precise values. The disadvantage of banded colour scales is that they can easily introduce artificial boundaries that may not exist in the data and can be misleading. Continuous colour scales (as long as they are perceptually-uniform) better let you see the actual variation of the data.

**Comment by xrmitchell** [comment]
is it possible to use a continuous colour scale for this project?
