### ISSUE TITLE
Do we keep the Px.x numbering?

### ISSUE THREAD

**Issue by gilesdring** [odileeds/ukpn-heat-street#6]
The Px.x numbering has been added for our traceability. Do we want to keep it in the final visualisation.

**Comment by slowe** [comment]
Good suggestion from @xrmitchell to put mention of which data pack in the description underneath the parameter.

**Comment by slowe** [comment]
The dropdown list for parameters now has grouping to reduce the duplication of labels. 
![dropdown](https://user-images.githubusercontent.com/299787/124163813-e4e40e00-da97-11eb-9e8c-43b3e9873bff.png)

Links to the specific data packs now get included in the description underneath rather than being in the label.

**Comment by xrmitchell** [comment]
It looks really good now, nice one

**Comment by slowe** [comment]
I think this issue is resolved.
